### ISSUE TITLE
Use of undeclared identifier 'data' on ios 

### ISSUE THREAD

**Issue by YvainVDP** [Alwinator/react-native-http-bridge-refurbished#11]
When I build with expo eas for IOS I have this error on the fastlane step
  

      ❌  (node_modules/react-native-http-bridge-refurbished/ios/RCTHttpServer.m:99:96)

       97 |                   body: (NSString *) body)
       98 | {
    >  99 |     GCDWebServerDataResponse* requestResponse = [[GCDWebServerDataResponse alloc] initWithData:data contentType:type];
          |                                                                                                ^ use of undeclared identifier 'data'
      100 |     requestResponse.statusCode = code;
      101 | 
      102 |     GCDWebServerCompletionBlock completionBlock = nil;
I use React-native-http-bridge-refurbished version 1.2.4
React-native 0.71.3

**Comment by YvainVDP** [comment]
Found the issue, it was because of the version 1.2.4, with the 1.2.3 version it works

**Comment by Alwinator** [comment]
Thank you for reporting! I think this is caused by the pull request https://github.com/Alwinator/react-native-http-bridge-refurbished/pull/9.

@vanLesson Can you please check this error?

**Comment by vanLesson** [comment]
@YvainVDP can you please provide more information about the environments  or provide a minimal reproduction project which includes the bug

**Comment by YvainVDP** [comment]
EAS is an Expo feature that give the ability to build and publish react native app to the app store without having a mac.
Install globally EAS `npm install -g eas-cli.`  Create a project with expo with `npx create-expo-app my-app` then link it with `eas login` (you have to make an account). 
Add the http bridge refurbished to the depedencies, maybe add the bridge in the code, not sure. 
Also add expo-linking to the depedencies with `npx expo install expo-linking`
Add to App.json
```
 "expo": {
    "scheme": "Nameofapp",
 "ios": {
      "bundleIdentifier": "",
      "buildNumber": ""
    },
}
```
And then push it to the app store with `eas submit --platform ios --auto-submit`. 
It will build on the EAS server on expo.dev and you can see the build process there.
I can't give you a minimal reproduction right now because the project I work on is not mine and I would need to create a resource of my own on the app store to reproduce the bug.
Hoping it will help

**Comment by ahlun** [comment]
Comparing 1.2.4 with previous commit 1.2.3, i think this single line was  accidentally deleted from `RCTHttpServer.m`

`NSData* data = [body dataUsingEncoding:NSUTF8StringEncoding];`

Simply add it back does the trick for me. Here's the patch file for your reference.

[react-native-http-bridge-refurbished+1.2.4.patch](https://github.com/Alwinator/react-native-http-bridge-refurbished/files/11242306/react-native-http-bridge-refurbished%2B1.2.4.patch)
